<?php
/**
 * Created by PhpStorm.
 * User: Nourhan
 * Date: 2019-03-29
 * Time: 8:00 AM
 */

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Storage;

class HomeController extends Controller
{
    public static $unWantedWords = array(
        "the", "a", ".", "to", "this", "is", "was", "that", "just", "then", "very", " "
    );

    public static function index(Request $request) {

        $data = Input::all();

        if($data['read_type'] == 2) {

            $fileName = $request->article_file->getClientOriginalName();

            $fileExtension = $request->article_file->getClientOriginalExtension();

            if(strtolower($fileExtension) == 'txt') {

                $path = $request->article_file->storeAs('articles-files', $fileName);
                $data['article_text'] = (string)Storage::get($path);

            } else {

                $storagePath = storage_path("app\articles-files\\".$fileName);
                $docObj = new DocxConversion($storagePath);
                $docText = $docObj->convertToText();
                $data['article_text'] = (string)$docText;
            }

        }

        $words = explode(" ", $data['article_text']);

        $politicsCount = 0;
        $sportsCount = 0;
        $healthsCount = 0;

        $politics = array(
            'government',
            'politics',
            'political',
            'party',
            'movement',
            'faction',
            'bloc',
            'liberal',
            'conservative',
            'neo-conservative',
            'country',
            'nation',
            'homeland',
            'citizen',
            'immigrant',
            'population',
            'democracy',
            'republic',
            'kingdom',
            'empire',
            'mandate',
            'colony',
            'dictatorship',
            'totalitarianism',
            'fascism',
            'communism',
            'socialism',
            'capitalism',
            'anarchism',
            'patriotism',
            'nationalism',
            'pan-Arab nationalism',
            'federal government',
            'local government',
            'coalition government',
            'authority',
            'legislative',
            'executive',
            'judicial',
            'constitution',
            'amendment',
            'veto',
            'position',
            'office',
            'president',
            'chairman',
            'prime minister',
            'governor',
            'ruler',
            'mayor',
            'monarch',
            'king',
            'prince',
            'crown prince',
            'His Majesty',
            'His Royal Highness',
            'tyrant',
            'despot',
            'ambassador',
            'minister',
            'deputy',
            'vice',
            'representative',
            'member',
            'official',
            'representative',
            'spokesman',
            'delegate',
            'envoy',
            'deputy',
            'agent',
            'councillor',
            'advisor',
            'secretary general',
            'leader',
            'embassy',
            'committee',
            'delegation',
            'council',
            'parliament',
            'the American Congress',
            'the American Senate',
            'the American House of Representatives',
            'the Supreme Court',
            'agency',
            'institution',
            'foundation',
            'organization',
            'group',
            'association',
            'the United Nations',
            'the General Assembly',
            'the Security Council',
            'resolution',
            'decision',
            'session',
            'the European Union',
            'Group of Eight',
            'World Health Organization',
            'International Monetary Fund',
            'World Bank',
            'World Trade Organization',
            'Human Rights Watch',
            'Amnesty International',
            'Doctors Without Borders',
            'the Red Cross',
            'the Red Crescent',
            'the Arab League',
            'Gulf Cooperation Council',
            'OPEC',
            'Hezbollah',
            'Hamas',
            'the Muslim Brotherhood',
            'Al-Aqsa Martyrs Brigade',
            'Popular Front for the Liberation of Palestine',
            'Al-Qaeda',
            'Islamic Jihad',
            'administration',
            'govt. agency or authority',
            'intelligence',
            'ministry',
            'ministry of defense',
            'ministry of the interior',
            'ministry of foreign affairs',
            'ministry of justice',
            'ministry of finance',
            'ministry of health',
            'ministry of agriculture',
            'ministry of education',
            'ministry of higher education',
            'ministry of civil services',
            'ministry of water resources and irrigation',
            'ministry of public works and housing',
            'ministry of economics and planning',
            'ministry of tourism and antiquities',
            'ministry of industry and trade',
            'ministry of communications and transportation',
            'ministry of energy and mineral resources',
            'ministry of Islamic affairs and endowments',
            'ministry of social development',
            'ministry of culture',
            'election',
            'campaign',
            'candidate',
            'competitor',
            'voter',
            'clean',
            'fair',
            'transparency',
            'election rigging',
            'fraud',
            'contribution',
            'referendum',
            'propaganda',
            'advertising',
            'slogan',
            'empty slogan',
            'debate',
            'voter turnout',
            'vote',
            'voice',
            'noise',
            'to vote',
            'poll',
            'opinion',
            'analysis',
            'statistics',
            'result',
            'half',
            'percentage',
            'majority',
            'the overwhelming majority',
            'to support',
            'to oppose',
            'supporting',
            'against',
            'issue',
            'affair',
            'law',
            'policy',
            'restrictions',
            'reform',
            'controversy',
            'scandal',
            'corruption',
            'corrupt',
            'negligence',
            'theft',
            'swindling',
            'bribery',
            'embezzlement',
            'fraud',
            'blackmail',
            'favoritism',
            'nepotism',
            'connections',
            'security',
            'safety',
            'peace',
            'stability',
            'protection',
            'unity',
            'equality',
            'independence',
            'sovereignty',
            'justice',
            'tolerance',
            'coexistence',
            'pluralism',
            'diversity',
            'freedom',
            'dignity',
            'conscience',
            'principle',
            'morals',
            'standard',
            'right',
            'human rights',
            'women rights',
            'minority rights',
            'the right to vote',
            'the right to a fair trial',
            'the right to privacy',
            'freedom of religion',
            'freedom of the press',
            'freedom of opinion',
            'freedom of expression',
            'oppression',
            'persecution',
            'repression',
            'tyranny',
            'prejudice',
            'discrimination',
            'sexism',
            'racism',
            'anti-Semitism',
            'homophobia',
            'torture',
            'massacre',
            'genocide',
            'ethnic cleansing',
            'female genital mutilation',
            'honor crime',
            'domestic violence',
            'sexual harassment',
            'rape',
            'sexual exploitation',
            'prostitution',
            'sex trafficking',
            'human trafficking',
            'slavery'
);

        $sports = array(
            'English',
            'hobby',
            'sport',
            'game',
            'crafts',
            'soccer',
            'ball',
            'team',
            'national team',
            'match',
            'stadium',
            'field',
            'midfield',
            'midfield line',
            'goal line',
            'side line',
            'off-side',
            'goal post',
            'crossbar',
            'goal',
            'consecutive goals',
            'player',
            'team captain',
            'midfielder',
            'goalkeeper',
            'attacker',
            'defender',
            'forward',
            'striker',
            'winger',
            'referee',
            'trainer',
            'coach',
            'kick',
            'shot',
            'free kick',
            'direct free kick',
            'penalty kick',
            'corner kick',
            'goal kick',
            'header',
            'dive',
            'win',
            'victory',
            'lose',
            'loss',
            'score a goal',
            'pass',
            'ball',
            'pass',
            'foul',
            'eliminate',
            'beat',
            'team',
            'ascend final',
            'equalize',
            'tie',
            'scoreless tie',
            'yellow card',
            'red card',
            'first half',
            'second half',
            'half-time',
            'World Cup',
            'FIFA',
            'amateur',
            'professional',
            'American football',
            'basketball',
            'volleyball',
            'baseball',
            'tennis',
            'hockey',
            'martial arts',
            'skiing',
            'ice-skating',
            'golf',
            'gymnastics',
            'mountain-climbing',
            'archery',
            'shooting',
            'skating',
            'running',
            'cricket',
            'polo',
            'horseback riding',
            'boxing',
            'wrestling',
            'weightlifting',
            'cycling',
            'swimming',
            'diving',
            'rowing',
            'surfing',
            'backgammon',
            'chess',
            'chess board',
            'king piece',
            'queen piece',
            'pawn piece',
            'knight piece',
            'rook piece',
            'castle piece',
            'bishop piece',
            'Check',
            'Checkmate',
            'stamp collecting',
            'gardening',
            'gambling',
            'fishing',
            'fishing rod',
            'hunting',
            'sewing',
            'cards',
            'spades',
            'diamonds',
            'clubs',
            'hearts',
            'ace',
            'king',
            'queen',
            'jack',
            'joker',
            'cheat',
            'shuffle',
            'deal',
            'to stay up late',
            'go out late',
            'spend time',
            'frequent',
            'place',
            'pass time',
            'stroll',
            'outing',
            'joke',
            'enjoy',
            'happy',
            'relax',
            'together',
            'appointment',
            'party',
            'costume party',
            'mask',
            'friend',
            'gift',
            'present',
            'invite',
            'occassion',
            'late',
            'time',
            'drunk',
            'alcoholic',
            'drunk',
            'high',
            'gambler',
            'play',
            'throw',
            'catch',
            'support',
            'compete',
            'advance',
            'progress',
            'move',
            'reflexive',
            'take a walk',
            'run',
            'climb',
            'swim',
            'sail',
            'fitness',
            'exercise',
            'warm-up',
            'lose weight',
            'competition',
            'race',
            'lap',
            'track',
            'championship',
            'champion',
            'point'
        );

        $healths = array(
            'medicine',
            'nursing',
            'doctor',
            'dentist',
            'surgeon',
            'nurse',
            'patient',
            'hospital',
            'clinic',
            'pharmacy',
            'ambulance',
            'disease',
            'chronic',
            'infectious',
            'contagious',
            'infection',
            'parasite',
            'cancer',
            'diabetes',
            'arthritis',
            'asthma',
            'AIDS',
            'heart attack',
            'coma',
            'clot',
            'stroke',
            'bird flu',
            'allergy',
            'cold',
            'sore throat',
            'appendicitis',
            'bronchitis',
            'hypertension',
            'arteosclerosis',
            'cirrhosis',
            'autism',
            'chicken pox',
            'leprosy',
            'kidney stone',
            'meningitis',
            'tuberculosis',
            'leukemia',
            'epilepsy',
            'osteoporosis',
            'symptom',
            'headache',
            'insomnia',
            'heartburn',
            'diarrhea',
            'stomach cramping',
            'constipation',
            'indigestion',
            'bruise',
            'burn',
            'sunburn',
            'laceration',
            'scratch',
            'graze',
            'cut',
            'wound',
            'boil',
            'swelling',
            'tumor',
            'inflammation',
            'infection',
            'dizziness',
            'vomiting',
            'nausea',
            'shock',
            'temperature',
            'fever',
            'degree',
            'broken',
            'arm',
            'benign',
            'malignant',
            'thermometer',
            'stethoscope',
            'X-ray',
            'blood pressure',
            'medicine',
            'medication',
            'pill',
            'tablet',
            'syrup',
            'antibiotic',
            'dose',
            'ointment',
            'vaccine',
            'gauze',
            'bandage',
            'dressing',
            'band-aid',
            'stitches',
            'cast',
            'splint',
            'crutch',
            'disinfectant',
            'anesthesia',
            'operation',
            'surgery',
            'amputation',
            'autopsy',
            'abortion',
            'hysterectomy',
            'heart',
            'transplant',
            'chemotherapy',
            'plastic surgery',
            'liposuction',
            'health',
            'sick',
            'ill',
            'healthy',
            'sound',
            'weak',
            'strong',
            'blind',
            'deaf',
            'paralyzed',
            'handicapped',
            'disabled',
            'mentally disabled',
            'scratch',
            'injure',
            'scratch',
            'mosquibite',
            'sting',
            'bite',
            'bite',
            'bleed',
            'feel',
            'pain',
            'emotion',
            'hurt',
            'pain',
            'throb',
            'injured',
            'bruise',
            'swell',
            'break',
            'sprain',
            'sneeze',
            'cough',
            'stuffed-up nose',
            'runny nose',
            'vomit',
            'prevention of',
            'examine medically',
            'medical examination',
            'measure',
            'inject',
            'shot',
            'injection',
            'sterilize',
            'diagnose',
            'prescribe',
            'prescription',
            'treat',
            'illness',
            'cure',
            'disease',
            'get sick',
            'get better'
        );

        foreach ($words as $word){

            foreach ($politics as $politic) {
                if(!in_array(strtolower(trim($word)), HomeController::$unWantedWords)
                    && !in_array(strtolower(trim($politic)), HomeController::$unWantedWords)
                    && strtolower(trim($word)) == strtolower(trim($politic))
                ) {
                    $politicsCount++;
                    break;
                }
            }

            foreach ($sports as $sport) {
                if(!in_array(strtolower(trim($word)), HomeController::$unWantedWords)
                    && !in_array(strtolower(trim($sport)), HomeController::$unWantedWords)
                    && strtolower(trim($word)) == strtolower(trim($sport))
                ) {
                    $sportsCount++;
                    break;
                }
            }

            foreach ($healths as $health) {
                if(!in_array(strtolower(trim($word)), HomeController::$unWantedWords)
                    && !in_array(strtolower(trim($health)), HomeController::$unWantedWords)
                    && strtolower(trim($word)) == strtolower(trim($health))
                ) {
                    $healthsCount++;
                    break;
                }
            }

        }

        if ($politicsCount > $sportsCount && $politicsCount > $healthsCount) {
            $articleType = 'Politic Article';
            $style = 'color: red; font-weight: bold; border: 3px solid red; line-height: 90px; text-align: center; height: 100px; width: 370px';
        } elseif ($sportsCount > $politicsCount && $sportsCount > $healthsCount) {
            $articleType = 'Sport Article';
            $style = 'color: green; font-weight: bold; border: 3px solid green; line-height: 90px; text-align: center; height: 100px; width: 370px';
        } elseif ($healthsCount > $politicsCount && $healthsCount > $sportsCount) {
            $articleType = 'Health Article';
            $style = 'color: blue; font-weight: bold; border: 3px solid blue; line-height: 90px; text-align: center; height: 100px; width: 370px';
        } elseif($politicsCount == 0 && $sportsCount == 0 && $healthsCount == 0) {
            $articleType = 'Other Type';
            $style = 'color: black; font-weight: bold; border: 3px solid black; line-height: 90px; text-align: center; height: 100px; width: 370px';
        }

        $result = array(
            'politic_count' => $politicsCount,
            'sport_count' => $sportsCount,
            'health_count' => $healthsCount,
            'article_type' => $articleType,
            'style' => $style
        );

        return view('result', ['result' => $result]);
    }
}